### ISSUE TITLE
Desktop command issue

### ISSUE THREAD

**Issue by StevenCaddy** [underwatergrasshopper/poe_exp_after_dot#47]
Getting this error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Lib\site-packages\poe_exp_after_dot\__main__.py", line 8, in <module>
    _execute()
  File "C:\Python312\Lib\site-packages\poe_exp_after_dot\__main__.py", line 5, in _execute
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\poe_exp_after_dot\__init__.py", line 95, in main
    return _main(argv if argv else [])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\poe_exp_after_dot\__init__.py", line 73, in _main
    raise exception
  File "C:\Python312\Lib\site-packages\poe_exp_after_dot\__init__.py", line 43, in _main
    exit_code = overlay.main(argv)
                ^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\poe_exp_after_dot\_Private\Overlay.py", line 326, in main
    raise ValueError(f"Incorrect command line argument. Unknown option \"{option_name}\".")
ValueError: Incorrect command line argument. Unknown option "--make-run-file".

when running this command py -3-64 -m poe_exp_after_dot --make-run-file

**Comment by underwatergrasshopper** [comment]
I assuming you have older version of overlay. Option `--make-run-file` is available on version 1.0.3.
To check version run `py -3-64 -m poe_exp_after_dot --version`.
